### ISSUE TITLE
[M0-01] Elección del lenguaje de programación

### ISSUE THREAD

**Issue by diagmatrix** [PabloBarTo/Empresa#6]
Hola! Trabajaré sobre tu proyecto para el objetivo 2.

¿Qué lenguaje de programación tenías pensado utilizar? A mí me parecen bien todos así de primeras.

**Comment by PabloBarTo** [comment]
Hola! Si te parece bien, me gustaría utilizar TypeScript.

**Comment by diagmatrix** [comment]
Sin problema :)

**Comment by PabloBarTo** [comment]
Como quieras, me da igual uno u otro. Por telegram al tenerlo en el móvil tardaría menos en contestarte que por correo pero el que prefieras.

**Comment by diagmatrix** [comment]
Pues por Telegram mejor entonces

**Comment by PabloBarTo** [comment]
Vale, mi id de telegram es @PabloXD_7
