### ISSUE TITLE
[HU1-01] ¿Qué es una plantilla?

### ISSUE THREAD

**Issue by diagmatrix** [PabloBarTo/Empresa#8]
Un equipo de fútbol se compone de una plantilla. Para componer una plantilla, las siguientes condiciones deben ser necesarias, según aparecen en #3 y por tratarse de ese deporte:

- Un presupuesto, que inicialmente es de 100M€.
- Un número de jugadores que compondrán el equipo, inicialmente vacío. Los jugadores se describen en #9.

**Comment by PabloBarTo** [comment]
Yo creo que las posiciones de los jugadores no me van a ayudar mucho para resolver este problema. Como menciono en #3 lo que más me interesa saber del jugador serían los puntos que realiza y su valor de mercado. Con eso yo creo que valdría.

**Comment by diagmatrix** [comment]
> Yo creo que las posiciones de los jugadores no me van a ayudar mucho para resolver este problema. Como menciono en #3 lo que más me interesa saber del jugador serían los puntos que realiza y su valor de mercado. Con eso yo creo que valdría.

Si entiendo bien, el problema es construcción de una plantilla. Entonces, ¿no es bastante necesario conocer la posición del jugador para, por ejemplo, únicamente buscar porteros, o no buscar delanteros puesto que se encuentra el óptimo en cuanto a valor? Hasta donde yo sé, no puedes en una plantilla de fantasy poner más jugadores de los posibles para una posición.

**Comment by PabloBarTo** [comment]
Sí, pero por ejemplo el número de jugadores en cada posición podría variar ya que existen muchas formaciones distintas. Por eso en la historia de usuario no menciono nada de las posiciones del jugador ni nada, si no que me centro en tener con el presupuesto del que dispongo los jugadores que en total me puedan hacer más puntos.
